### ISSUE TITLE
Make SEOmetafields app extend Guillotine

### ISSUE THREAD

**Issue by rymsha** [enonic/app-metafields#114]
- Remove "Headless mode" setting from site.xml: Nope we will not do this

```[tasklist]
### Tasks
- [x] Extend Guillotine schema by adding a new field called "metaFields" under "content"
- [x] Remove the service that serves the data
- [x] Change SeoMetaFieldsScript.tsx in site-enonic-next to use "seo.x" fields from the schema injected by the app
- [x] Test the new version of the app on Enonic site locally
- [x] Use the next.js metadata structure
- [x] Return the actual image content for openGraph and twitter on toplevel
- [x] Use the same keys as nextjs metadata fields, but type them as JSON
- [x] The Xdata should not be on templatefolder or media
- [x] Remove siteConfig frontpage fallback, and use site content override image instead
- [x] outboundDependencies query for media:image
- [x] locale and siteName on top
- [x] openGraph.article.expirationTime, modifiedTime and publishedTime
- [ ] Write upgrade doc for any breaking changes
- [ ] https://github.com/enonic/app-metafields/issues/113
- [ ] https://github.com/enonic/app-metafields/issues/116
- [ ] https://github.com/enonic/app-metafields/issues/118
- [ ] https://github.com/enonic/app-metafields/issues/119
- [ ] https://github.com/enonic/app-metafields/issues/120
- [ ] https://github.com/enonic/app-metafields/issues/121
- [ ] https://github.com/enonic/app-metafields/issues/122
- [ ] https://github.com/enonic/app-metafields/issues/123
- [ ] https://github.com/enonic/app-metafields/issues/124
- [ ] https://github.com/enonic/app-metafields/issues/125
- [ ] https://github.com/enonic/app-metafields/issues/126
- [ ] https://github.com/enonic/app-metafields/issues/127
```

**Comment by ComLock** [comment]
- Remove "Headless mode" setting from site.xml: Nope we will not do this
- [x] Extend Guillotine schema by adding a new field called "metaFields" under "content"
- [x] Remove the service that serves the data
- [x] Change SeoMetaFieldsScript.tsx in site-enonic-next to use "seo.x" fields from the schema injected by the app
- [x] Test the new version of the app on Enonic site locally
- [x] Use the next.js metadata structure
- [x] Return the actual image content for openGraph and twitter on toplevel
- [x] Use the same keys as nextjs metadata fields, but type them as JSON
- [x] The Xdata should not be on templatefolder or media
- [x] Remove siteConfig frontpage fallback, and use site content override image instead
- [x] outboundDependencies query for media:image
- [x] locale and siteName on top
- [x] title is always just the full computed title from metafields
- [x] openGraph.article.expirationTime, modifiedTime and publishedTime
